# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Azuresonar'
    organization: 'yaswanthgajjala9347'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'yaswanthgajjala9347_Azuresonar'
    cliProjectName: 'Azuresonar'
    cliSources: '.'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME'       
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'  

steps:
- checkout: self
  fetchDepth: 0


      
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

